/*
 * This source file was generated by the Gradle 'init' task
 */
package stratostrike;

import stratostrike.Controller.GameLauncher;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        GameLauncher launcher = new GameLauncher();
        launcher.launchGame();
    }
}
