/*
 * This source file was generated by the Gradle 'init' task
 */
package stratostrike;

import stratostrike.Domain.Model.Player;
import stratostrike.Domain.Model.StratoCraftGame;
import stratostrike.Domain.Model.Army.Army;
import stratostrike.Domain.Model.Army.Factory.ArmyFactory;
import stratostrike.Domain.Model.Army.Factory.ArmyManager;
import stratostrike.View.*;
import stratostrike.ViewModel.MakeTurn;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        //insitnziazione giocatori e navi e attacchi
        Player player1 = new Player("Player1",1);
        Player player2 = new Player("Player2",2);

        //creazione partita
        StratoCraftGame game = new StratoCraftGame(player1, player2);
        System.out.println("Welcome to " + game.getPlayer1().getUsername() + " vs " + game.getPlayer2().getUsername()
                + " Stratostrike Game!");

                
        /*     CODICE PER TESTARE IL TURNO
        //aggiunta navi all'armata
        Fighter fighter = new Fighter();
        
        Fighter fighter2 = new Fighter();
        
        fighter.addAction(pointAttack);
        fighter2.addAction(pointAttack);
        player1.getArmy().addShip(fighter2);
        player1.getArmy().addShip(fighter);
       //settaggio navi sulla board      
        game.getBoard().placeShip(fighter2,2,2,0);   
        game.getBoard().placeShip(fighter,4,4,0);
        //inzio del turno
        MakeTurn turn = new MakeTurn(game);
        
        turn.playTurn();
        turn.selectShip();
        turn.showActions();
        turn.selectAction();
        turn.showAreaEffect();
        */

        // CODICE PER TESTARE LE FACTORY
        /*
        MakeTurn turn = new MakeTurn(game);
        InputView view = new InputView();

        ArmyFactory factory = view.scegliArmata();
        Army miaArmata = factory.createArmy();

        view.stampaStatoArmata(miaArmata);
        game.getCurrentPlayer().setArmy(miaArmata);
        game.getBoard().setupRandomArmyPlacement(miaArmata);

        // Creo un'armata nemica e la metto sulla board per test
        Army enemyArmy = ArmyManager.getFactory("Cyber").createArmy();
        game.getBoard().setupRandomArmyPlacement(enemyArmy);

        // turno
        turn.playTurn();
        
        turn.selectShip();
        turn.selectAction();
        turn.showAreaEffect();
        turn.executeAction();

        //turno
        turn.playTurn();
        
        turn.selectShip();
        turn.selectAction();
        turn.showAreaEffect();
        turn.executeAction();
        

        */


        //CODICE PER TESTARE LA VIEW
        ArmyFactory factory = view.scegliArmata();
        Army miaArmata = factory.createArmy();

        view.stampaStatoArmata(miaArmata);
        game.getCurrentPlayer().setArmy(miaArmata);
        game.getBoard().setupRandomArmyPlacement(miaArmata);

        // Creo un'armata nemica e la metto sulla board per test
        Army enemyArmy = ArmyManager.getFactory("Cyber").createArmy();
        game.getBoard().setupRandomArmyPlacement(enemyArmy);

        boardView.printBoard();
        SelectionView selectionView = new SelectionView(game);
        selectionView.showActions();
        selectionView.selectAction();
    }


}
