package stratostrike;

public enum GameEvent {
    SELECT_ARMY,
    COMPOSE_ARMY,
    TURN_STARTED,
    SELECT_SHIP,
    SELECT_ACTION,
    SELECT_POSITION,
    EXECUTE_ACTION,  
    SHIP_DESTROYED,
    SHIP_HIT,
    SHIP_MISSED,
    TURN_ENDED,
    GAME_WON,
    GAME_LOST,
    PLAYER1_TURN_STARTED,
    PLAYER2_TURN_STARTED,
    SPECIAL_ACTION_SELECTED
}
